import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SiderProvider ,GetPostProvider} from "@/contexts";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GetPostProvider>
      <SiderProvider>
        {children}
      </SiderProvider>
      </GetPostProvider>
        </body>
    </html>
  );
}
